baseURL = 'https://abmfy.github.io/'
languageCode = 'zh-CN'
theme = 'paper'

title = "abmfy's space"
description = "A paradise far removed from the hubbub of life."

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 15

recent_posts_number = 3

[params.homeInfoParams]
Title = "Hello from abmfy! 👋"

