baseURL = 'https://abmfy.github.io/'
languageCode = 'zh-CN'
theme = 'ananke'

title = "abmfy's space"

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 10

[params]
  description = "A paradise far removed from the hubbub of life."
  recent_posts_number = 3
